replicaCount: 1

image:
  repository: grekodocker/darkreader
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 6969

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

env:
  environment: "production"
  masterPasswordsFile: "/app/data/passwd.json"
  adminFilePath: "/var/secrets/admins.txt"
  sessionFile: "/app/data/sessions.json"
  textPath: "/app/data/texts"

storage:
  mountPath: /app/data
  # storageClass: ""   # leave unset to use the cluster default StorageClass
  size: 1Gi

backup:
  schedule: "0 0 * * 0"  # every Sunday at midnight
  # storageClass: ""      # leave unset to use the cluster default StorageClass
  size: 1Gi
  retainCount: 8          # keep 8 weekly snapshots (~2 months)

terminationGracePeriodSeconds: 2

ingress:
  enabled: true
  host: dr.alexgr.space
  tls:
    secretName: dr-alexgr-space-tls
